# data1

In [1]:
from scipy.io.wavfile import read

rate1, data1 = read("speechA1.wav")#音声ファイルの読み込み
rate2,data2  = read("speechA2.wav")

In [3]:
import numpy as np
x = np.array([[data1],[data2]])
x=np.asmatrix(x)

matrix([[-3.35738959],
        [-3.95349884]])

In [403]:
#白色化
x=x-np.mean(x,axis=1)
Σ=1/x.shape[1]*np.dot(x,x.T)
l, P = np.linalg.eig(Σ )
# D=np.diag(l), D=P.T*Σ*P
L=l**(-0.5)
P=P
V=np.dot(np.dot(P,np.diag(L)),P.T)
z=np.dot(V,x)

In [404]:
W=np.array([[0.0,0.0],[0.0,0.0]])#Wの初期化
flag=0
ε=0.0000000000000000001
while flag< 2:
    w=np.random.rand(2,1)
    w=w/np.linalg.norm(w)
    while True:
        p=w
        w=np.dot(z,np.power(w.T*z,3).T)*1/(z.shape[1])-3*w  # 𝔼[𝒛(𝒘⊤𝒛)3] − 3𝒘　(計算の次元を等しくするためにw.T*z,3を転置した)
        w= w/np.linalg.norm(w)
        if (((w[0]-p[0])**2<ε and (w[1]-p[1])**2<ε)or( (w[0]+p[0])**2<ε and (w[1]+p[1])**2<ε)):
            if  (flag==0):
                flag+=1
                W[0]=w.T
                break
            if (flag==1):
                if  (((w[0]-W[0][0])**2>ε or (w[1]-W[0][1])**2>ε) and ((w[0]+W[0][0])**2>ε or (w[1]+W[0][1])**2>ε)):
                    flag+=1
                    W[1]=w.T
                break
        
W

array([[ 0.00579528,  0.99998321],
       [ 0.99962184, -0.02749867]])

In [81]:
y=np.dot(W,z)
outdata1=y[0].T
outdata2=y[1].T#それぞれのデータを元の形に戻す

In [182]:
from scipy.io.wavfile import write

write("data1_1.wav",rate1 , outdata1)
write("data1_2.wav",rate2 , outdata2)

In [ ]:
rate,data5  = read("music1.wav")
rate6,data6  = read("music2.wav")

# data2

In [183]:
rate3,data3  = read("speechB1.wav")
rate4,data4  = read("speechB2.wav")
rate5,data5  = read("speechB3.wav")

In [187]:
x2= np.array([[data3],[data4],[data5]])
x2=np.asmatrix(x2)

In [189]:
x2=x2-np.mean(x2,axis=1)
Σ2=1/x2.shape[1]*np.dot(x2,x2.T)
l2, P2 = np.linalg.eig(Σ2 )
# D=np.diag(l), D=P.T*Σ*P
L2=l2**(-0.5)
P2=P2
V2=np.dot(np.dot(P2,np.diag(L2)),P2.T)
z2=np.dot(V2,x2)

matrix([[ 1.00000000e+00,  1.04427593e-14, -8.38094678e-15],
        [ 1.04427593e-14,  1.00000000e+00,  2.72834510e-14],
        [-8.38094678e-15,  2.72834510e-14,  1.00000000e+00]])

In [391]:
W2=np.array([[0.0,0.0,0.0],[0.0,0.0,0.0],[0.0,0.0,0.0]])#Wの初期化
flag=0
ε=0.000000000000000001
while flag< 3:
    w=np.random.rand(3,1)
    w=w/np.linalg.norm(w)
    while True:
        p=w
        w=np.dot(z2,np.power(w.T*z2,3).T)*1/(z2.shape[1])-3*w  # 𝔼[𝒛(𝒘⊤𝒛)3] − 3𝒘　(計算の次元を等しくするためにw.T*z,3を転置した)
        w= w/np.linalg.norm(w)
        if (((w[0]-p[0])**2<ε and (w[1]-p[1])**2<ε and (w[2]-p[2])**2<ε)or( (w[0]+p[0])**2<ε and (w[1]+p[1])**2<ε and (w[2]+p[2])**2<ε)):
            if  (flag==0):
                flag+=1
                W2[0]=w.T
                break
            elif (flag==1):
                if  (((w[0]-W2[0][0])**2>ε or (w[1]-W2[0][1])**2>ε or (w[2]-W2[0][2])**2>ε  ) and ((w[0]+W2[0][0])**2>ε or (w[1]+W2[0][1])**2>ε or  (w[2]+W2[0][2])**2>ε )):
                    flag+=1
                    W2[1]=w.T
                    break
                else:
                    w=np.random.rand(3,1)
            elif (flag==2):
                if  (((w[0]-W2[0][0])**2>ε or (w[1]-W2[0][1])**2>ε or (w[2]-W2[0][2])**2>ε  ) and ((w[0]+W2[0][0])**2>ε or (w[1]+W2[0][1])**2>ε or  (w[2]+W2[0][2])**2>ε )):
                    if  (((w[0]-W2[1][0])**2>ε or (w[1]-W2[1][1])**2>ε or (w[2]-W2[1][2])**2>ε  ) and ((w[0]+W2[1][0])**2>ε or (w[1]+W2[1][1])**2>ε or  (w[2]+W2[1][2])**2>ε )):
                        flag+=1
                        W2[2]=w.T
                        break
                    else:
                        w=np.random.rand(3,1)
                else:
                    w=np.random.rand(3,1)
                
        
W2
                        


array([[ 2.54713966e-04,  5.30074734e-03,  9.99985919e-01],
       [-7.31243751e-03,  9.99933705e-01, -8.89459762e-03],
       [ 9.99616988e-01,  2.03787964e-02, -1.87238371e-02]])

In [392]:
y2=np.dot(W2,z2)
outdata3=y2[0].T
outdata4=y2[1].T
outdata5=y2[2].T
#それぞれのデータを元の形に戻す

In [393]:
from scipy.io.wavfile import write

write("data2_1.wav",rate3 , outdata3)
write("data2_2.wav",rate4 , outdata4)
write("data2_3.wav",rate5 , outdata5)

# data3


In [395]:
rate6,data6  = read("music1.wav")
rate7,data7  = read("music2.wav")

In [396]:
x3= np.array([[data6],[data7]])
x3=np.asmatrix(x3)

In [397]:
#白色化
x3=x3-np.mean(x3,axis=1)
Σ3=1/x3.shape[1]*np.dot(x3,x3.T)
l3, P3 = np.linalg.eig(Σ3 )
# D=np.diag(l), D=P.T*Σ*P
L3=l3**(-0.5)
P3=P3
V3=np.dot(np.dot(P3,np.diag(L3)),P3.T)
z3=np.dot(V3,x3)

In [398]:
W3=np.array([[0.0,0.0],[0.0,0.0]])#Wの初期化
flag=0
ε=0.0000000000000000001
while flag< 2:
    w=np.random.rand(2,1)
    w=w/np.linalg.norm(w)
    while True:
        p=w
        w=np.dot(z3,np.power(w.T*z3,3).T)*1/(z3.shape[1])-3*w  # 𝔼[𝒛(𝒘⊤𝒛)3] − 3𝒘　(計算の次元を等しくするためにw.T*z,3を転置した)
        w= w/np.linalg.norm(w)
        if (((w[0]-p[0])**2<ε and (w[1]-p[1])**2<ε)or( (w[0]+p[0])**2<ε and (w[1]+p[1])**2<ε)):
            if  (flag==0):
                flag+=1
                W3[0]=w.T
                break
            if (flag==1):
                if  (((w[0]-W3[0][0])**2>ε or (w[1]-W3[0][1])**2>ε) and ((w[0]+W3[0][0])**2>ε or (w[1]+W3[0][1])**2>ε)):
                    flag+=1
                    W3[1]=w.T
                break
        
W

array([[ 0.00579528,  0.99998321],
       [ 0.99962184, -0.02749867]])

In [399]:
y3=np.dot(W3,z3)
outdata6=y3[0].T
outdata7=y3[1].T#それぞれのデータを元の形に戻す

In [400]:
from scipy.io.wavfile import write

write("data3_1.wav",rate6 , outdata6)
write("data3_2.wav",rate7 , outdata7)